const snackbarTypes = {
  REVIEW_SUBMISSION_ERROR: 'REVIEW_SUBMISSION_ERROR',
  REVIEW_SUBMISSION_SUCCESS: 'REVIEW_SUBMISSION_SUCCESS',
  SETTINGS_ERROR: 'SETTINGS_ERROR',
  SETTINGS_SUCCESS: 'SETTINGS_SUCCESS',
  SUBMISSION_ERROR: 'SUBMISSION_ERROR',
  VOTING_ERROR: 'VOTING_ERROR',
  VOTING_SUCCESS: 'VOTING_SUCCESS',
};

export default snackbarTypes;
