const ContestStatus = {
  NOT_STARTED: 'NOT_STARTED',
  SUBMISSIONS_OPEN: 'SUBMISSIONS_OPEN',
  SUBMISSIONS_CLOSED: 'SUBMISSIONS_CLOSED',
  VOTING_OPEN: 'VOTING_OPEN',
  VOTING_CLOSED: 'VOTING_CLOSED',
  RESULTS_CERTIFIED: 'RESULTS_CERTIFIED',
};

module.exports = ContestStatus;
